### ISSUE TITLE
Expose ability to enable remote write receiver for Prometheus controller

### ISSUE THREAD

**Issue by leifmadsen** [rhobs/observability-operator#160]
**Request**

Enable the remote-write receiver functionality (https://prometheus.io/docs/prometheus/latest/feature_flags/#remote-write-receiver) for the Prometheus controller in Observability Operator

**Use Case**

Future versions of OpenStack will implement an `openstack observability` CLI command which will deploy Prometheus in Agent mode to locally scrape and remote-write data without providing local data storage or TSDB functionality. Storage of data from the cloud into a centralized data system (without the need to have tenants etc as this is an administrative domain environment) for the purposes of monitoring for anomalies in the OpenStack platform in order to alert administrators of issues and to provide basic graphing capabilities is the reason for this request.

**Comment by simonpasquier** [comment]
:wave: IIUC you want use the Observability Operator to deploy a Prometheus instance that would receive metrics from Prometheus agents?

**Comment by leifmadsen** [comment]
> wave IIUC you want use the Observability Operator to deploy a Prometheus instance that would receive metrics from Prometheus agents?

Correct. Instead of collecting metrics on OSP and transporting them via QDR and exposing them via Smart Gateway middleware for scraping by Prometheus on OCP, we want to scrape locally on OCP and remote-write them to another Prometheus for the storage domain.
