### ISSUE TITLE
Set <resource>Selector and <resource>Namespace for all resources in Prometheus that ObO creates

### ISSUE THREAD

**Issue by sthaha** [rhobs/observability-operator#283]
Usecase: 

> We currently make use of the probe_success metric for some of our PrometheusRules. My understanding is that `probe_success `is only made available via the blackbox exporter and Probe CRs. I can't figure out how to set the `probeSelector` and `probeNamespaceSelector` fields on the Prometheus Spec using the MonitoringStack CR.

**Comment by simonpasquier** [comment]
it can/should also include ScrapeConfig resources
