### ISSUE TITLE
Streamline the building process for new catalogs

### ISSUE THREAD

**Issue by fpetkovski** [rhobs/observability-operator#32]
When adding a bundle to a catalog, the pipeline needs to know whether a catalog image already exists. If a catalog exists, the catalog building command needs to execute opm with the `--from-index` flag. When a catalog does not exist yet, the `--from-index` flag should be omitted. This makes it cumbersome to test the build process with new catalogs because the pipeline itself needs to be adjusted.

The make target which builds the catalog can check whether a catalog image already exists using the `docker manifest inspect <catalog-image>` command and execute opm with the appropriate flags depending on the outcome.

https://github.com/rhobs/monitoring-stack-operator/blob/main/.github/olm-publish/action.yaml#L45
https://github.com/rhobs/monitoring-stack-operator/blob/main/Makefile#L184

**Comment by sthaha** [comment]
During development we do sometimes want to start with an empty catalog. So the ability to set `FIRST_RELEASE` is worth keeping but I do agree that given that we overwrite the catalog image (i.e. the catalog images aren't versioned; which is a possibility to consider), the `docker inspect <image>` can be done in pipeline itself.

**Comment by jan--f** [comment]
@sthaha Iiuc this is no longer an issue since switching to file based catalogs?

**Comment by sthaha** [comment]
Closing this as we switched to FBC as @jan--f mentioned.
