### ISSUE TITLE
Migrate PodDisruptionBudget to v1

### ISSUE THREAD

**Issue by sthaha** [rhobs/observability-operator#332]
See: 
* https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/3084#issuecomment-1676521068
* https://kubernetes.io/docs/reference/using-api/deprecation-guide/#poddisruptionbudget-v125

This validation warning stood out when publishing 0.0.25 (see PR). 

```
Value observability-operator.v0.0.25: this bundle is using APIs whichwere deprecated and removed in v1.25. 
More info: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-25. 
Migrate the API(s) for poddisruptionbudgets: 
(["ClusterServiceVersion.Spec.InstallStrategy.StrategySpec.ClusterPermissions[2].Rules[13]"])
```

**Comment by simonpasquier** [comment]
It doesn't seem right as I can't see any reference to the deprecated v1beta1 API version :thinking:
