### ISSUE TITLE
Clarify if a redhat subscription is required to use this operator

### ISSUE THREAD

**Issue by bo0ts** [rhobs/observability-operator#489]
The latest version in the https://github.com/redhat-openshift-ecosystem/community-operators-prod is the outdated `0.0.28`.

The latest version is only available from the redhat operators index and lists `Valid Subscriptions: ["OpenShift Kubernetes Engine", "OpenShift Container Platform", "OpenShift Platform Plus"]`.

This repository does not make any mention of a required subscription. What is the case?

**Comment by jan--f** [comment]
You can install the versions from the Red Hat operators index freely. If you want to use Red Hats production support service, one of the listed subscriptions is required. The code is free and open, support is not :)
Not sure that needs further clarification?

**Comment by bo0ts** [comment]
@jan--f After some discussion on the okd-dev and okd-users Slack channel I frankly think that this is not true.

Operators in the RedHat Operators index require a subscription and a pull secret for `registry.redhat.io`. If you only have a developer subscription and install this in a production environment you possibly have a subscription violation.

**Comment by jan--f** [comment]
Reopening this after further discussion. We should add a note that installing via the RH catalog requires a subscription.

**Comment by simonpasquier** [comment]
Closing it again. Version 0.4.1 of the operator installed from the Red Hat catalog indicates the valid subscriptions:
 
![image](https://github.com/user-attachments/assets/f38a1cb6-81bf-4f35-bff1-38d4b9c5aa64)
