### ISSUE TITLE
Updating UIPlugin resource status causes the reconciliation to loop

### ISSUE THREAD

**Issue by iNecas** [rhobs/observability-operator#564]
I've noticed that when enabling the UIPlugin, the operator does one reconciliation after another.

It seems the problem is due to always setting the conditions with new last transition time timestamp, leading to new generation of the resource and new reconciliation loop.

https://github.com/rhobs/observability-operator/blob/main/pkg/controllers/uiplugin/controller.go#L214.

I suspect other stacks have similar issue as well.

**Comment by simonpasquier** [comment]
Late here but is there a COO ticket for this issue?

**Comment by jgbernalp** [comment]
I just  created one: https://issues.redhat.com/browse/COO-385
